set_charger_current:
  # If the service accepts entity IDs, target allows the user to specify entities by entity, device, or area.
  target:
    entity:
      integration: emporia_vue
      device_class: outlet
  # Different fields that your service accepts
  fields:
    # Key of the field
    current:
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 6
      # The default field value
      default: 6
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        number:
          min: 6
          max: 48
