set_charger_current:
  # Service name as shown in UI
  name: Set Charger Current
  # Description of the service
  description: Sets the charging current for an EVSE/Charger.
  # If the service accepts entity IDs, target allows the user to specify entities by entity, device, or area. If `target` is specified, `entity_id` should not be defined in the `fields` map. By default it shows only targets matching entities from the same domain as the service, but if further customization is required, target supports the entity, device, and area selectors (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector parameters will automatically be applied to device and area, and device selector parameters will automatically be applied to area.
  target:
    entity:
      integration: emporia_vue
      device_class: outlet
      multiple: false
    device:
      manufacturer: Emporia
      model: VVDN01
      multiple: false
  # Different fields that your service accepts
  fields:
    # Key of the field
    current:
      # Field name as shown in UI
      name: Charging Current
      # Description of the field
      description: The desired charging current in Amps.
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: false
      # Example value that can be passed for this field
      example: 6
      # The default field value
      default: 6
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        number:
          min: 6
          max: 48
